// Software model of the CPU caches, for measuring how well the sheet force kernel uses them (the hardware counters
// of Apple silicon need root). The kernel's memory accesses are replayed through a two-level set-associative LRU
// model with the geometry of the machine (M4 performance core: L1D 128 KB, L2 16 MB per cluster, 128-byte lines):
//   * hit rates of L1 and L2, lines fetched from L2 / from memory, bytes moved per triangle;
//   * line utilisation: the share of the bytes of every line brought into L1 that the kernel touched before the line
//     was evicted (1.0: every byte of every fetched line was used; a scattered AoS layout wastes most of each line).
// The access streams are generated by walking the kernel's data structures in the kernel's order (reads and writes of
// every record field, node and output), for the pre-optimisation kernel (Shell records + per-class force arrays,
// separate edge and hinge loops) and for the current one (ShellKernel: hot records, hinge records, slots, gather).
#pragma once

#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

namespace bl::phys {

class SoftBody;

struct CacheStats {
    uint64_t accesses = 0;              // loads and stores (each touching one or more lines)
    uint64_t l1_hits = 0, l1_misses = 0;
    uint64_t l2_hits = 0, l2_misses = 0;
    uint64_t bytes_touched = 0;         // bytes the kernel actually read or wrote
    uint64_t lines_evicted = 0, bytes_used_evicted = 0; // L1 lines evicted / flushed, and their touched bytes
    double l1_hit_rate() const { return l1_hits + l1_misses ? (double)l1_hits / (double)(l1_hits + l1_misses) : 0; }
    double l2_hit_rate() const { return l2_hits + l2_misses ? (double)l2_hits / (double)(l2_hits + l2_misses) : 0; }
    double line_utilisation(int line) const { return lines_evicted ? (double)bytes_used_evicted / ((double)lines_evicted * line) : 0; }
};

class CacheSim {
public:
    struct Level {
        size_t size;
        int ways;
    };
    CacheSim(Level l1 = {128 * 1024, 8}, Level l2 = {16u * 1024 * 1024, 16}, int line = 128);
    void access(const void* p, size_t bytes);  // a load or a store (write-allocate)
    void flush();                              // evict everything (counts the utilisation of the resident lines)
    void reset_stats() { m_stats = CacheStats{}; }
    const CacheStats& stats() const { return m_stats; }
    int line() const { return m_line; }

private:
    struct Way {
        uint64_t tag = ~0ull;
        uint64_t lru = 0;
        uint64_t used[2] = {0, 0};  // touched bytes of the line (L1 only; up to 128 bytes)
    };
    struct Cache {
        int sets = 0, ways = 0;
        std::vector<Way> w;
    };
    bool lookup(Cache& c, uint64_t line_addr, bool l1, uint32_t off, uint32_t len);
    void mark(Way& w, uint32_t off, uint32_t len);
    int m_line;
    int m_shift;
    uint64_t m_clock = 0;
    Cache m_l1, m_l2;
    CacheStats m_stats;
};

// Cache behaviour of one evaluation of all triangles of `b` (every triangle due): after a warm-up pass (the steady
// state of a simulation: the same data every short step), one measured pass.
struct KernelCacheReport {
    CacheStats cur, ref;                // current kernel (with the gather), pre-optimisation kernel
    size_t shells = 0, nodes = 0, hinges = 0;
    double cur_bytes_per_tri = 0, ref_bytes_per_tri = 0;       // bytes touched per triangle
    double cur_l2_bytes_per_tri = 0, ref_l2_bytes_per_tri = 0; // bytes brought into L1 per triangle
    double cur_mem_bytes_per_tri = 0, ref_mem_bytes_per_tri = 0; // bytes brought from memory (L2 misses) per triangle
    double working_set_cur = 0, working_set_ref = 0;             // bytes of the arrays involved
    std::string text() const;
};
KernelCacheReport measure_kernel_cache(SoftBody& b);

} // namespace bl::phys
